<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>magik</string>
		<string>Magik</string>
		<string>MAGIK</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(_for|_if|_method)</string>
	<key>foldingStopMarker</key>
	<string>(_endloop|_endif|_endmethod)</string>
	<key>name</key>
	<string>Magik</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#methods</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#symbols</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#packages</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtins</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtins</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(def_slotted_exemplar|def_package|define_shared_constant)\b</string>
					<key>name</key>
					<string>support.function.magik</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#self</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(#)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.magik</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.magik</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(_if|_else|_elif|_endif|_loop|_endloop|_for|_over|_leave|_return|_then|_protect|_endprotect)\b</string>
					<key>name</key>
					<string>keyword.control.magik</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(_private|_optional|_method|_endmethod|_proc|_endproc|_is|_local)\b</string>
					<key>name</key>
					<string>keyword.other.magik</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[&lt;&lt;|&gt;&gt;|-|\+|\*|/|=|&lt;&gt;|~]{1}</string>
					<key>name</key>
					<string>keyword.operator.magik</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(_true|_false|_unset|_maybe)\b</string>
					<key>name</key>
					<string>constant.language.magik</string>
				</dict>
			</array>
		</dict>
		<key>methods</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\w+)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.magik</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.function.identifier.magik</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#symbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#methods</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#methods</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.magik</string>
				</dict>
			</array>
		</dict>
		<key>packages</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+:\w+</string>
					<key>name</key>
					<string>storage.modifier.magik</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.magik</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.magik</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+:\w+)|((_package)\s+(\w+))</string>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>variable.parameter.magik</string>
				</dict>
			</array>
		</dict>
		<key>self</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(_self)\b</string>
					<key>name</key>
					<string>variable.language.magik</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.magik</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\.</string>
							<key>name</key>
							<string>constant.character.escape.magik</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>symbols</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.symbol.magik</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:[a-zA-Z]+([0-9]|_|-|[a-zA-Z])*)</string>
					<key>name</key>
					<string>keyword.control.untitled</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.magik</string>
	<key>uuid</key>
	<string>6b5b3a62-bc9f-452e-9887-8a78e98f044e</string>
</dict>
</plist>
